spring.application.name=springbootbackend
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
spring.datasource.username=root
spring.datasource.password=Kalyan@123
spring.jpa.hibernate.ddl-auto=update